{:species_option=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:species_option,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String,
   :autoscanned_defaults=>["analytic"]},
 :species_file=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:species_file,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String,
   :autoscanned_defaults=>[]},
 :species_time=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:species_time,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>[]},
 :ntspec=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:ntspec,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer,
   :autoscanned_defaults=>[2]},
 :convergetol=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:convergetol,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>[]},
 :grad_option=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:grad_option,
   :must_pass=>
    [{:test=>"kind_of? String",
      :explanation=>"This variable must be a string."}],
   :type=>:String,
   :autoscanned_defaults=>["tgrads"]},
 :dti=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:dti,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>[]},
 :dte=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:dte,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>[]},
 :tite=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:tite,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>
    ["temp_perturb(idx:idx+ncc-1,1)/temp_perturb(idx:idx+ncc-1,2)", "ti/te"]},
 :rln=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:rln,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>[1.0]},
 :nedge=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:nedge,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>[]},
 :powerin=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:powerin,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>[0.0]},
 :src_ratio=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:src_ratio,
   :must_pass=>
    [{:test=>"kind_of? Numeric",
      :explanation=>
       "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
   :type=>:Float,
   :autoscanned_defaults=>[]},
 :write_smooth=>
  {:should_include=>"true",
   :description=>nil,
   :help=>nil,
   :code_name=>:write_smooth,
   :must_pass=>
    [{:test=>"kind_of? String and FORTRAN_BOOLS.include? self",
      :explanation=>
       "This variable must be a fortran boolean. (In Ruby this is represented as a string: e.g. '.true.')"}],
   :type=>:Fortran_Bool,
   :autoscanned_defaults=>[]}}
